In [7]:
import numpy as np

# generate numpy array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [8]:
# generate multidimensional arrays called matrix
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
# generate shape(3, 2) matrix with random values
c = np.random.random((3, 2))
print(c)

[[0.03166255 0.24069505]
 [0.57291538 0.52402795]
 [0.44563676 0.60985195]]


In [27]:
# access value of matrix(0, 1)
print(c[0, 1])

0.24069504830354183


In [15]:
# reshape matrix shape(3, 2) to shape(6)
d = c.reshape(6)
print(d)

[0.06213249 0.06563555 0.72270632 0.62925781 0.73198907 0.98721797]


In [23]:
# generate shape(5, 5) matrix with random zero
e = np.zeros((5, 5))
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
# update value of matrix
e[2, 2] = 5
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
# add scalar to matrix 
# you can also use "scalar + matrix"
f = 3
g = np.add(f, e)
print(g)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 8. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [41]:
# multiply matrix by scalar
# you can also use "matrix * scalar"
f = 3
h = np.multiply(e, f)
print(h)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [42]:
# multiply matrix by matrix
# you should practice other case
i = np.random.rand(3, 4)
j = np.random.rand(4, 2)
k = np.matmul(i, j)
print(k)

[[0.63879168 1.09880247]
 [0.58120588 1.3672375 ]
 [0.36066373 1.53225898]]
